name: 'Deploy test-environment to staging'

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy-staging:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
